import 'dart:io';

void main(List<String> args) {
  if (args.isEmpty || args.contains('--help') || args.contains('-h')) {
    _printUsage();
    return;
  }

  final featureName = _normalizeFeatureName(args.first);
  final classPrefix = _toPascalCase(featureName);
  final identifierPrefix = _toCamelCase(featureName);
  final directory = Directory('lib/src/features/$featureName');

  if (directory.existsSync()) {
    stderr.writeln('Feature "$featureName" already exists.');
    exitCode = 1;
    return;
  }

  directory.createSync(recursive: true);

  _writeFile(
    '${directory.path}/${featureName}_page.dart',
    _pageTemplate(
      featureName: featureName,
      classPrefix: classPrefix,
      identifierPrefix: identifierPrefix,
    ),
  );
  _writeFile(
    '${directory.path}/${featureName}_providers.dart',
    _providersTemplate(
      identifierPrefix: identifierPrefix,
      classPrefix: classPrefix,
    ),
  );
  _writeFile(
    '${directory.path}/README.md',
    _readmeTemplate(featureName: featureName, classPrefix: classPrefix),
  );

  stdout.writeln('Created feature "$featureName" in ${directory.path}.');
  stdout.writeln('Next: register ${classPrefix}Page in app_router.dart.');
}

void _printUsage() {
  stdout.writeln('Usage: dart run scripts/new_feature.dart <feature_name>');
  stdout.writeln('Example: dart run scripts/new_feature.dart profile');
}

String _normalizeFeatureName(String input) {
  final name = input
      .trim()
      .replaceAll(RegExp(r'[^A-Za-z0-9]+'), '_')
      .replaceAll(RegExp(r'_+'), '_')
      .replaceAll(RegExp(r'^_|_$'), '')
      .toLowerCase();

  if (name.isEmpty || RegExp(r'^[0-9]').hasMatch(name)) {
    stderr.writeln('Feature name must start with a letter.');
    exit(64);
  }

  return name;
}

String _toPascalCase(String input) {
  return input
      .split('_')
      .where((part) => part.isNotEmpty)
      .map((part) => part[0].toUpperCase() + part.substring(1))
      .join();
}

String _toCamelCase(String input) {
  final pascal = _toPascalCase(input);
  return pascal[0].toLowerCase() + pascal.substring(1);
}

void _writeFile(String path, String content) {
  final file = File(path);
  file.writeAsStringSync(content);
}

String _pageTemplate({
  required String featureName,
  required String classPrefix,
  required String identifierPrefix,
}) {
  return '''
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../shared/widgets/page_frame.dart';
import '../../shared/widgets/section_card.dart';
import '${featureName}_providers.dart';

class ${classPrefix}Page extends ConsumerWidget {
  const ${classPrefix}Page({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final state = ref.watch(${identifierPrefix}ControllerProvider);

    return PageFrame(
      storageId: '$featureName',
      title: '$classPrefix',
      subtitle: 'Replace this placeholder with the feature experience.',
      children: [
        SectionCard(
          title: 'State',
          icon: Icons.auto_awesome_motion_outlined,
          children: [
            Text(state.message),
          ],
        ),
      ],
    );
  }
}
''';
}

String _providersTemplate({
  required String identifierPrefix,
  required String classPrefix,
}) {
  return '''
import 'package:flutter_riverpod/flutter_riverpod.dart';

final ${identifierPrefix}ControllerProvider =
    NotifierProvider<${classPrefix}Controller, ${classPrefix}State>(
  ${classPrefix}Controller.new,
);

class ${classPrefix}Controller extends Notifier<${classPrefix}State> {
  @override
  ${classPrefix}State build() {
    return const ${classPrefix}State(message: 'Ready');
  }
}

class ${classPrefix}State {
  const ${classPrefix}State({required this.message});

  final String message;
}
''';
}

String _readmeTemplate({
  required String featureName,
  required String classPrefix,
}) {
  return '''
# $classPrefix Feature

Generated by `scripts/new_feature.dart`.

## Files

- `${featureName}_page.dart`: screen entry.
- `${featureName}_providers.dart`: Riverpod state entry.

## Checklist

- Register the route in `lib/src/core/routing/app_router.dart`.
- Add navigation only if this feature should be top-level.
- Move API/cache calls into `lib/src/data/repositories/` when shared.
- Add widget or provider tests before replacing placeholder UI.
''';
}
